DEFAULT:
  downloads:
  - label: DCS Logs
    directory: '%USERPROFILE%\Saved Games\{server.instance.name}\logs'
    pattern: dcs*.log
  - label: DCSServerBot Logs
    directory: .
    pattern: dcssb-{server.node.name}.log*
  - label: Missions
    directory: '%USERPROFILE%\Saved Games\{server.instance.name}\Missions'
    pattern: '*.miz'
  - label: Tacview
    directory: '%USERPROFILE%\Documents\Tacview'
    pattern: Tacview-*.acmi
  - label: Chat Logs
    directory: '%USERPROFILE%\Saved Games\{server.instance.name}\logs'
    pattern: chat.*log*
  - label: Main Config Files
    directory: .\config
    pattern: '*.yaml'
  - label: Plugin Config Files
    directory: .\config\plugins
    pattern: '*.yaml'
  - label: Service Config Files
    directory: .\config\services
    pattern: '*.yaml'
