commands:
- cmd:
    args: -w {instance}
    cwd: C:\Program Files\Eagle Dynamics\DCS World OpenBeta Server\bin
    exe: DCS.exe
  name: dcs
  params:
  - instance
  roles:
  - DCS Admin
- cmd:
    cwd: C:\
    exe: dir
    shell: true
  hidden: true
  name: dir
  roles:
  - Admin
  - DCS Admin
