DEFAULT:
  FunkMan:
    IMAGEPATH: ../FunkMan/funkpics/
    install: ../FunkMan
  num_landings: 5
  num_rows: 10
  persistent_board: false
  persistent_channel: '123456789'
  ratings:
    (OK): 3
    --: 2
    B: 2.5
    C: 0
    OK: 4
    OWO: 2
    WO: 1
    _OK_: 5
DCS.openbeta_server:
  Moose.AIRBOSS:
    basedir: airboss
    delete_after: 180
    grades: AIRBOSS-{carrier}_LSOGrades.csv
    trapsheets: '*AIRBOSS-{carrier}_Trapsheet-{name}_{unit_type}*.csv'
instance2:
  FunkMan:
    basedir: trapsheets
    delete_after: 180
