DEFAULT:
  nudge:
    delay: 600
    display_time: 20
    display_type: popup
    message: 'This awesome server is presented to you by http://discord.gg/myfancylink. Come and join us!'
    recipients: '!@everyone'
  on_birth:
    display_time: 20
    display_type: popup
    message: '{player.name}, welcome to {server.name}!'
DCS.openbeta_server:
  on_join:
    message: 'Welcome to our public server! Teamkills will be punished.'
