DEFAULT:
  RootFolder: '%USERPROFILE%\Documents\OvGME\RootFolder'
  SavedGames: '%USERPROFILE%\Documents\OvGME\SavedGames'
DCS.openbeta_server:
  packages:
  - name: Community_A-4E-C
    source: SavedGames
    version: 2.0.1
instance2:
  packages:
  - name: Community_A-4E-C
    source: SavedGames
    version: latest
