DEFAULT:
  decay:
  - days: 60
    weight: 0
  - days: 30
    weight: 0.25
  - days: 3
    weight: 0.75
  - days: 0
    weight: 1
  flightHoursWeight:
  - time: 0
    weight: 1.4
  - time: 3
    weight: 1
  - time: 10
    weight: 0.7
  punishments:
  - action: ban
    delay: 10
    points: 100
  - action: kick
    delay: 10
    points: 60
  - action: move_to_spec
    delay: 10
    points: 40
  - action: credits
    delay: 10
    penalty: 10
    points: 12
  - action: warn
    points: 1
  unban: 75
DCS.openbeta_server:
  exemptions:
  - discord: '@everyone'
  forgive: 30
  penalties:
  - AI: 18
    action: move_to_spec
    event: kill
    human: 30
    reason: Killing a team member
  - AI: 12
    event: collision_kill
    human: 20
    reason: Killing a team member during a collision
  - AI: 8
    event: friendly_fire
    human: 12
    reason: Friendly fire on a team member
  - AI: 1
    event: collision_hit
    human: 5
    reason: Colliding with a team member
instance2:
  exemptions:
  - discord: '@everyone'
  forgive: 30
  penalties:
  - AI: 18
    event: kill
    human: 30
    reason: Killing a team member
  - AI: 12
    event: collision_kill
    human: 20
    reason: Killing a team member during a collision
  - AI: 8
    event: friendly_fire
    human: 12
    reason: Friendly fire on a team member
  - AI: 1
    event: collision_hit
    human: 5
    reason: Colliding with a team member
  decay:
