DEFAULT:
  warn:
    text: '!!! {item} will {what} in {when} !!!'
    times:
    - 600
    - 300
    - 60
    - 10
DCS.openbeta_server:
  schedule:
    00-24: YYYYYYY
instance2:
  onMissionEnd: load:Scripts/net/end.lua
  onMissionStart: load:Scripts/net/start.lua
  onShutdown: run:shutdown /r
  restart:
    local_times:
    - 00:00
    - 04:00
    - 08:00
    method: rotate
    populated: true
    settings:
      00:00-07:59: Winter,Nighttime
      08:00-11:59: Summer,Noon
  schedule:
    00-12: YYYYYYY
    12-24: NNNNNNN
instance3:
  restart:
    method: restart_with_shutdown
    mission_time: 480
    populated: false
    settings:
    - Winter,Late Evening,Heavy Storm
    - Summer,Morning,Slight Breeze
  schedule:
    00-12: NNNNNNN
    12-24: YYYYYYY
mission:
  schedule:
    '18:00': NNNNNNY
