DEFAULT:
  VIP:
    audit: true
    discord:
    - Admin
    - DCS Admin
    slots: 2
  restricted:
  - discord: Donators
    message: This slot is reserved for Donators!
    unit_type: artillery_commander
  - discord: Donators
    message: This slot is reserved for Donators!
    unit_type: forward_observer
  - discord: Donators
    message: This slot is reserved for Donators!
    unit_type: instructor
  - discord: '@everyone'
    message: This slot is reserved for members of http://invite.link!
    unit_type: observer
DCS.openbeta_server:
  restricted:
  - costs: 10
    group_name: Rookie
    points: 10
  - costs: 10
    group_name: Veteran
    points: 20
  - costs: 30
    group_name: Ace
    points: 50
  use_reservations: true
